services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: xenomech
      POSTGRES_PASSWORD: xenomech
      POSTGRES_DB: mocha
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mocha-network

  web:
    build: .
    command:
      - ./build.sh
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - mocha-network

networks:
  mocha-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
