services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: xenomech
      POSTGRES_PASSWORD: xenomech
      POSTGRES_DB: mocha
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mocha-network

  django:
    build: .
    command:
      - ./build.sh
    expose:
      - 8000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - mocha-network

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - django
    networks:
      - mocha-network

networks:
  mocha-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
