services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: xenomech
      POSTGRES_PASSWORD: xenomech
      POSTGRES_DB: mocha
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mocha-network

  django:
    build: .
    command:
      - ./build.sh
    expose:
      - 8000
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    depends_on:
      - db
    networks:
      - mocha-network

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - static_volume:/app/staticfiles
    depends_on:
      - django
    networks:
      - mocha-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    networks:
      - mocha-network
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  mocha-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  static_volume:
    driver: local
