databases:
  - name: mocha
    plan: free
    databaseName: mocha
    user: xenomech

services:
  - type: web
    plan: free
    name: mocha
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mocha.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mocha
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4